//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELMS_WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document_Details
    {
        public int Doc_id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<int> Discipline_id { get; set; }
        public string Author { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> Doc_TypeId { get; set; }
    
        public virtual Discipline Discipline { get; set; }
        public virtual Document_Type Document_Type { get; set; }
    }
}
