//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELMS_WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Details
    {
        public int User_id { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public Nullable<long> Phone_Number { get; set; }
        public string Interest { get; set; }
        public string Email_id { get; set; }
        public string Password { get; set; }
        public string Bank_Name { get; set; }
        public Nullable<long> Credit_Card { get; set; }
        public Nullable<bool> Subscription { get; set; }
        public Nullable<bool> Admin { get; set; }
    }
}
